L =['Michael','Sarah','Tracy']
print(L[0],L[1],L[2])
print(L[0:3])
print(L[:3])
print(L[1:3])
print(L[-2])
L =list(range(100))
print(L)
print(L[:10])
print(L[10:20])
print(L[-20:-1])
print(L[:])
print('ABCDEFG'[:3])
print('ABCDEFG'[::2])